### ISSUE TITLE
Support for Ultramodern 5 Redux?

### ISSUE THREAD

**Issue by devinnasar** [MrBrentRogers/UM5-Ultramodern5-OGL#2]
Dias Ex Machina have released a revision of UM5 that modifies some of the content from the original, as well as adding a great deal of new content. Do you have access to this resource, would you like it, and if so, would you be interested in a discussion for adding that content to your Foundry Module? I am running a game that includes UM5 redux content and would love to use your module.

**Comment by MrBrentRogers** [comment]
Hey devinnasar,
Is the Revision part of their OGL\SRD? I have the full version myself but wanted to make sure the module was within licensing restrictions - so only the items released for public usage. 

If they did re-release a product with their OGL, could you send me the link and I'd love to work with you on including the additional content!

Sincerely, 
Brent.
