### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by LayonRodrigues** [MrBrentRogers/UM5-Ultramodern5-OGL#3]
--- Module installed. But it didn't add anything to Foundry, or compendium, or sheet template, or anything.
Imcompatibility issue with Compendium Folders module.

**Comment by LayonRodrigues** [comment]
And how I import the new skills to the sheet character?

**Comment by MrBrentRogers** [comment]
Hi. I use Compendium Folders, awesome module itself, and have not encountered any issues. The UM5 module is just compendium packs and doesn't do anything else on so I don't see how it could fail without another module hiding content.

To import skills onto character sheets you can just drag & drop them from the compendium - same as spells & features from the DnD5e SRD compendiums. 

Hope this helps.
